# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Descriptografar grandes segredos
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.UNITY_LICENSE }}
      # Este comando é apenas um exemplo para mostrar seu segredo sendo impresso
      # Certifique-se de remover quaisquer declarações impressas de seus segredos. O GitHub
      # não oculta segredos que usam essa alternativa.
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/secrets/my_secret.json
