  
name: Teste
on: [push]	
jobs:	
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:	
       # Checkout
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            lfs: true

      # Cache
        - uses: actions/cache@v1.1.0
          with:
            path: Library
            key: Library
      
        #- name: Unity - Test runner
          #uses: webbertakken/unity-test-runner@v1.7
          #env:
          #  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
         # with:
        #   customParameters: -nographics
       #    unityVersion: 2020.1.0f1
           
        - name: Unity - Builder
          uses: webbertakken/unity-builder@v1.4
          env:
             UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          with:
            unityVersion: 2020.1.0f1
            targetPlatform: StandaloneWindows64
      
