  
name: Teste
on: [push]	
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:	
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:	
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Unity - Test runner
        uses: webbertakken/unity-test-runner@v1.7
        id: testRunner
        with:
           customParameters: -nographics
           unityVersion: 2020.1.0f1
      - uses: actions/upload-artifact@v1
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}
           
      - name: Unity - Builder
        uses: webbertakken/unity-builder@v1.4
        with:
          unityVersion: 2020.1.0f1
          targetPlatform: StandaloneWindows64
          customParameters: -nographics
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
      
